name: GitHub Actions Test Build

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  configure:
    name: Configure Environments
  
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.json.outputs.matrix }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Echo Context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Read JSON
      id: json
      run: |
        echo "::set-output name=matrix::$(jq -c "[.[] | select(.environment == \"prod\")]" environments.json)"
      
    - name: JFrog
      uses: jfrog/setup-jfrog-cli@v1

    - run: jfrog --version && env
    
    - run: echo "${{ github.event.release.tag_name }}"

  install:
    name: Install ${{ matrix.environment }}

    runs-on: ubuntu-latest

    needs: configure

    strategy:
      matrix:
        include: ${{ fromJson(needs.configure.outputs.matrix) }}
      max-parallel: 2
        
    environment:
      name: ${{ matrix.environment }}

    steps:
    - name: Show Matrix Values
      run: echo "${{ matrix.resourceGroup }}" && echo "${{ matrix.clusterName }}" && echo "${{ secrets.ENVIRONMENT }}" && echo "${{ github.event.inputs.home }}"
