name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: echo 'Building...'
          
  deploy-dev:
    runs-on: ubuntu-latest
    
    environment: "Development"

    steps:
    - name: Deploy
      run: echo "Deployed to ${{ secrets.ENVIRONMENT }}"
      
  deploy-stage:
    runs-on: ubuntu-latest
        
    environment: "Stage"
    
    needs: "build"

    steps:
    - name: Deploy
      run: echo "Deployed to ${{ secrets.ENVIRONMENT }}"
      
  deploy-prod:
    runs-on: ubuntu-latest
    
    environment: "Production"
    
    needs: "deploy-stage"

    steps:
    - name: Deploy
      run: echo "Deployed to ${{ secrets.ENVIRONMENT }}"
      
      
