name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.json.outputs.matrix }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Read JSON
      id: json
      run: |
        echo "::set-output name=matrix::$(jq -c . environments.json)"

  install:
    runs-on: ubuntu-latest

    needs: configure

    strategy:
      matrix:
        includes: ${{ fromJson(needs.configure.outputs.matrix) }}
        
    environment:
      name: ${{ matrix.name }}

    steps:
    - name: Show Matrix Values
      run: echo "${{ matrix.resourceGroup }}" && echo "${{ matrix.clusterName }}" && echo "${{ secrets.ENVIRONMENT }}"
