name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      region:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      credentials:
        required: true
        
jobs:
  configure:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.json.outputs.matrix }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Filter Environments
      id: json
      run: |
        #echo "::set-output name=matrix::$(jq -c "{\"include\":[.[] | select(.environment == \"${INPUT_ENVIRONMENT}\")]}" environments.json | jq -R .)"
        echo "::set-output name=matrix::{\"include\":[{\"environment\":\"dev\",\"region\":\"east\",\"resourceGroup\":\"ct-n-zeaus-loy-custlogin-rg\",\"clusterName\":\"ct-n-zeaus-loy-custlogin-aks\"},{\"environment\":\"dev\",\"region\":\"west\",\"resourceGroup\":\"ct-n-zweus-loy-custlogin-rg\",\"clusterName\":\"ct-n-zweus-loy-custlogin-aks\"}]}"
      
  deploy:
    runs-on: ubuntu-latest
    needs: configure

    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}

    steps:
    - name: Deploy 
      run: |
        echo "Deploying to..."
        echo "environment: ${{ inputs.environment }}"
        echo "region: ${{ inputs.region }}"
        echo "tag: ${{ inputs.tag }}"
