name: Infrastructure Job

on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'Tool'
        default: 'logger'
        required: true

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Development
            value: development
          - name: Stage
            value: staging
          - name: Production
            value: production
    environment:
       name: ${{ matrix.name }}
    steps:
    - name: Run
      run: echo "This is ${{ matrix.value }}"
          
  install-dev:
    runs-on: ubuntu-latest
    
    environment: "Development"

    steps:
    - name: Run
      run: echo "Ran ${{ github.event.inputs.tool }} on ${{ secrets.environment }}"
      
  install-stage:
    runs-on: ubuntu-latest
    
    environment: "Stage"

    steps:
    - name: Run
      run: echo "Ran ${{ github.event.inputs.tool }} on ${{ secrets.environment }}"
      
  install-prod:
    runs-on: ubuntu-latest
    
    environment: "Production"

    steps:
    - name: Run
      run: echo "Ran ${{ github.event.inputs.tool }} on ${{ secrets.environment }}"

