name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
      region:
        description: 'Region'
        required: true
      tag:
        description: 'Tag'
        required: true

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.tag }} to ${{ github.event.inputs.environment }} ${{ github.event.inputs.region }}
    uses: jjustinic/actions-test/.github/workflows/deploy.yaml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      region: ${{ github.event.inputs.region }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      credentials: ${{ secrets.ENVIRONMENT }}
