name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
      region:
        description: 'Region'
        required: true
      tag:
        description: 'Tag'
        required: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml@main
    with:
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      tag: ${{ inputs.tag }}
    secrets:
        credentials: ${{ secrets.ENVIRONMENT }}
