on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]

name: Release Event

jobs:
  show_event:
    name: Show Event

    runs-on: ubuntu-latest

    steps:
      - name: Payload Info
        uses: Dovyski/payload-info-action@v1

